###Get all Books
GET http://localhost:3000/books

###Get One Book By Id
GET http://localhost:3000/books/1

###Create a Book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "ABC",
  "author": "Nam CT",
  "description": "Hihi Do ngoc"
}

###Delete a Book By ID
DELETE http://localhost:3000/books/1

###Update a Book By ID = 1
PUT http://localhost:3000/books/1
